config/routes.rb
Correlate::Application.routes.draw do
  devise_for :users
  resources :interests, only: [:index, :create, :update] do
    post :correlate, on: :collection
  end

  root :to => 'interests#index'
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  has_many :user_interests, dependent: :destroy
  attr_accessible :name
end

app/models/related.rb
class Related < ActiveRecord::Base
  belongs_to :user
  belongs_to :paired, :class_name => 'User'
  attr_accessible :count, :paired, :correlation

  scope :sorted, order("correlation DESC")

  def self.correlate
    self.destroy_all
    User.all.each do |user1|

      User.all.each do |user2|
        unless user2 == user1
          # Get the intersection (similar) and union (total) of the users interests
          similar_interests = user1.interests.map(&:id) & user2.interests.map(&:id)
          total_interests = user1.interests.map(&:id) | user2.interests.map(&:id)

          # Calulate the correlation
          jaccard_correlation = (similar_interests.count.to_f/total_interests.count.to_f).round(3)

          # Store the results for each user
          user1.related.create(count: similar_interests.count, correlation: jaccard_correlation, paired: user2)
        end
      end

    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :twitter

  validates :twitter, presence: true

  has_many :user_interests, dependent: :destroy
  has_many :interests, through: :user_interests
  has_many :related, dependent: :destroy

  def next
    User.where("id > ?", self.id).order(:id).first
  end
end

app/models/user_interest.rb
class UserInterest < ActiveRecord::Base
  belongs_to :user
  belongs_to :interest
  attr_accessible :interest, :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  respond_to :html

  def index
    @interests = current_user.interests if user_signed_in?
  end

  def create
    @interest = Interest.find_by_name(params[:interest][:name]) || Interest.new(params[:interest])
    respond_to do |format|
      if @interest.save
        current_user.user_interests.create(interest: @interest) unless current_user.interests.include?(@interest)
        format.html { redirect_to(root_url, notice: 'Interests added, now update your matches.') }
      else
        format.html { redirect_to(root_url, notice: 'There was error, please try again.') }
      end
    end
  end

  def update
    @interest = Interest.find(params[:id])
    respond_to do |format|
      if @interest.update_attributes(params[:interest])
        format.html { redirect_to(@interest, :notice => 'Interest was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def correlate

    Related.correlate

    redirect_to root_url, notice: "Your matches have been updated."
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/views/interests/index.html.haml
- if user_signed_in?
  .page-header
    %h2 Find people similar to you
  
  .row
    .span4
      = form_for :interest do |f|
        = f.label :name, "Add your interests"
        = f.text_field :name
    .span4
      .update
        = link_to "Update your Matches", correlate_interests_path, class: "btn btn-success", method: :post
      .matches
        %ul.unstyled
          - current_user.related.sorted.each do |related|
            %li= "@#{related.paired.twitter} (similarity #{related.correlation})"
    .span4
      %h3 My Interests
      %ul.unstyled
        - current_user.interests.each do |interest|
          %li= interest.name
- else
  .hero-unit
    .inner
      %h1 Find people similar to you
      %p Sign up, enter your interests and connect with similar people
      %p
        = link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-large"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Correlate
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          .brand
            = link_to "Correlate", root_url
          %ul.nav
            - if user_signed_in?
              %li= link_to "Sign Out", destroy_user_session_path
            - else
              %li= link_to "Create Account", new_user_registration_path
              %li= link_to "Sign In", new_user_session_path
        
      
    .container
      .content{role: "main"}
        = yield
    